### ISSUE TITLE
fbterm: the systemd fbterm@.service unit can be written shorter

### ISSUE THREAD

**Issue by ghost** [crondog/arch-flo#16]
_Not an issue, more of a suggestion._

systemd allows you to reuse the texts of existing units via `.include`. The [fbterm@.service](https://github.com/crondog/arch-flo/blob/master/fbterm/getty%40.service) can be converted to [something like that](https://gist.github.com/kalterfive/d4eb6b428d1a8bb9d2e1443797c8b745#file-fbterm-service).

Thank you.

**Comment by crondog** [comment]
Thanks for the suggestion
