### ISSUE TITLE
Using a normal chroot instead of a file system image

### ISSUE THREAD

**Issue by depau** [crondog/arch-flo#3]
I was wondering, why use an image when we can directly write stuff in /data? data is an ext4 file system, just like Arch's image, we can just chroot into it and that would do it, wouldn't it?
That would solve a lot of problems, like too much allocated storage for arch or not enough space in the image...

@willcast what do you think?

**Comment by crondog** [comment]
I like to have it in an image because it keeps it separate from android
which is the whole point of this project. My next plan is to partition
/data in half and have arch on one half. I dont like the idea of mixing os
together. I was also thinking of putting arch on a usb stick and boot from
that.

**Comment by depau** [comment]
It's not like they are mixed together: it's still a chroot, Android's not gonna touch Arch because it's hidden by multirom (unless you're root and you mess in /data/media/0/multirom).
I don't know however how to make that work with MultiROM, I guess I'll figure it out...

**Comment by depau** [comment]
I created a fork of the arch install scripts that solve some issues and install arch's image into multirom by default. It does not install a kernel nor the rom_info.txt, so it needs configuration before being bootable, but chroot works out of the box.
Other changes include:
- hostname is now "arch-flo"
- DNS is now OpenDNS
- SELinux is set to permissive before chrooting into Arch and reset afterwards, as it's a pain in the ass when you build stuff from aur or try to use fakeroot.

https://github.com/Davideddu/nexus-7-2013-arch-scripts/tree/multirom

**Comment by depau** [comment]
This issue can be closed too as I added instuctions to the readme on how to do it.
