### ISSUE TITLE
Help needed troubleshooting

### ISSUE THREAD

**Issue by depau** [crondog/arch-flo#4]
I started everything back from scratch. I created my image in /data/media/0/multirom/roms/ArchLinux so that I don't need to use fastboot to boot it. I built the drivers, built the initramfs (I edited init so that it looked for the image in the right place), pushed a kernel I previously build from your repo (I built it in March, from your "working" branch), then followed all the instructions in the README to get wifi, adb, etc working, and the instructions in ArchLinux's wiki to autologin and run xorg on login.
However I'm not getting anything: no USB serial console, no ADB, no autologin, no usb0, no nothing.

This is my last_kmsg. I just saw some messages from systemd that I didn't notice before, I guess I'll check them and let you know here.

http://paste.ubuntu.com/7908214/

**Comment by depau** [comment]
This is my last last_kmsg, after I fixed all the problems with systemd.
http://paste.ubuntu.com/7908598/

It still doesn't login to the virtual console, I don't know why.

EDIT: never mind, it does log in. It doesn't start xorg however. Weird. I can tell that because I inserted this in my bash_profile

```
echo -e "Bash started" >> logins
uname -a >> logins
date >> logins
echo >> logins
```

and this is the content of logins:

```
Bash started
Linux arch-flo 3.4.0-gc6b0a89 #1 SMP PREEMPT Thu Mar 13 19:24:38 EDT 2014 armv7l GNU/Linux
Wed Jul 30 15:30:42 MDT 2014

Bash started
Linux localhost 3.4.0-cyanogenmod-gde758a7 #26 SMP PREEMPT Tue Jun 17 14:02:10 CEST 2014 armv7l GNU/Linux
Wed Jul 30 15:35:04 MDT 2014
```

The last one is the chroot login, obviously, because it's running under CyanogenMod's kernel. I'll change it so that it also puts the first line of dmesg, so that it shows who built the kernel (me or the CM build bot).

I guess it will be my job to troubleshoot Xorg then. Hopefully tonight my computer and electricity provide will be good and it will build a new kernel, and I'll see whether the serial console works or not.

**Comment by crondog** [comment]
Use my mr1 branch kernel. It fixes that error you are having. It has
patches which fix that acl error

**Comment by depau** [comment]
It's building off the new branch now, thanks.

**Comment by depau** [comment]
Ok, I have the new kernel built and finally I can connect to the USB serial console (still no ADB though).
Everything will be easier now...

**Comment by depau** [comment]
I solved the issue. I just forgot to install startx :/
Now everything works perfectly. Actually not everything. I can't get the wifi working: there are only two network interfaces: loopback and dummy0 (which is a virtual ethernet interface).
However I think I'll be able to connect to the Internet through Bluetooth.

Soon (hopefully) I'll make a fork and add an updated xorg.conf with updated screen size so that some apps will update their DPI ('cause I don't have a microscope ;) ) and if I remember what Xrandr python bindings I previously used I'll add an autorotate script.

**Comment by depau** [comment]
I still cannot get neither bluetooth or wifi working. I have a dummy0 interface, and no usb0 on the computer.
The post says that bluez5 is supported, but bluetoothctl doesn't find the adapter. I'll try with bluez4.

**Comment by crondog** [comment]
Are you loading the modules?

modprobe wlan //loads wifi and bluetooth modules
echo 1 > /sys/module/hci_smd/parameters/hcismd_set //enables bluetooth

**Comment by depau** [comment]
No I'm not, nobody said that.
I wasn't aware of that module.

On August 1, 2014 7:42:00 AM CEST, crondog notifications@github.com wrote:

> Are you loading the modules?
> 
> modprobe wlan //loads wifi and bluetooth modules
> echo 1 > /sys/module/hci_smd/parameters/hcismd_set //enables bluetooth
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/crondog/arch-flo/issues/4#issuecomment-50850790

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by crondog** [comment]
It says to get wifi working you need to load firmware.service which does all of this.

**Comment by depau** [comment]
Look, I have no wlan module...

On August 1, 2014 7:42:00 AM CEST, crondog notifications@github.com wrote:

> Are you loading the modules?
> 
> modprobe wlan //loads wifi and bluetooth modules
> echo 1 > /sys/module/hci_smd/parameters/hcismd_set //enables bluetooth
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/crondog/arch-flo/issues/4#issuecomment-50850790

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by depau** [comment]
http://s30.postimg.org/bw5b5e4w1/IMG_20140801_095648.jpg

On August 1, 2014 9:57:48 AM CEST, Davide Depau me@davideddu.org wrote:

> Look, I have no wlan module...
> 
> On August 1, 2014 7:42:00 AM CEST, crondog notifications@github.com
> wrote:
> 
> > Are you loading the modules?
> > 
> > modprobe wlan //loads wifi and bluetooth modules
> > echo 1 > /sys/module/hci_smd/parameters/hcismd_set //enables bluetooth
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/crondog/arch-flo/issues/4#issuecomment-50850790
> 
> ## 
> 
> Sent from my Android device with K-9 Mail. Please excuse my brevity.

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by crondog** [comment]
You need to build them like you do with the zimage. 

ARCH=arm CROSS_COMPILE=~/android/system/prebuilts/gcc/linux-x86/arm/arm-eabi-4.7/bin/arm-eabi- make LOCALVERSION= -j8 modules

ARCH=arm CROSS_COMPILE=~/android/system/prebuilts/gcc/linux-x86/arm/arm-eabi-4.7/bin/arm-eabi- make -j8 INSTALL_MOD_STRIP=1 modules_install INSTALL_MOD_PATH=~/android/arch-flo/modules 

Or you can change CONFIG_MODULES to n so everything is compiled in the kernel.

**Comment by depau** [comment]
I think I'll build them in the kernel so that I don't have to install, and also enable Atheros Bluetooth ath3k and rt73 just in case it doesn't work (I have those two dongles).

So basically I have to run
make modules
make modules_install

Plus all the environ to cross compile?

On August 1, 2014 10:01:29 AM CEST, crondog notifications@github.com wrote:

> You need to build them like you do with the zimage. 
> 
> ARCH=arm
> CROSS_COMPILE=~/android/system/prebuilts/gcc/linux-x86/arm/arm-eabi-4.7/bin/arm-eabi-
> make LOCALVERSION= -j8 modules
> 
> ARCH=arm
> CROSS_COMPILE=~/android/system/prebuilts/gcc/linux-x86/arm/arm-eabi-4.7/bin/arm-eabi-
> make -j8 INSTALL_MOD_STRIP=1 modules_install
> INSTALL_MOD_PATH=~/android/arch-flo/modules 
> 
> Or you can change CONFIG_MODULES to n so everything is compiled in the
> kernel.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/crondog/arch-flo/issues/4#issuecomment-50859184

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by depau** [comment]
Ok, I'm building the new zimage with modules=n, adb enabled and swap enabled. I also need to find the option/patch to enable charging while an otg device is connected.

Oh and by the way, the hardware acceleration is _not_ working. Even though glxgears works, glxinfo | grep OpenGL says that the driver is VMware softpipe. Not a big deal, you just need to configure the wm appropriately, but it sucks because Kivy runs slow.

On August 1, 2014 10:01:29 AM CEST, crondog notifications@github.com wrote:

> You need to build them like you do with the zimage. 
> 
> ARCH=arm
> CROSS_COMPILE=~/android/system/prebuilts/gcc/linux-x86/arm/arm-eabi-4.7/bin/arm-eabi-
> make LOCALVERSION= -j8 modules
> 
> ARCH=arm
> CROSS_COMPILE=~/android/system/prebuilts/gcc/linux-x86/arm/arm-eabi-4.7/bin/arm-eabi-
> make -j8 INSTALL_MOD_STRIP=1 modules_install
> INSTALL_MOD_PATH=~/android/arch-flo/modules 
> 
> Or you can change CONFIG_MODULES to n so everything is compiled in the
> kernel.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/crondog/arch-flo/issues/4#issuecomment-50859184

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by depau** [comment]
I read your last message with the phone, so I thought LOCALVERSION was a variable :)
I got the concept now...

**Comment by tina-nova** [comment]
Hey, I have a problem booting with the mr1 kernel. It gives off kernel messages but never loads the console. Also, the redraw speed of these kernel messages is sluggish and piece by piece.

**Comment by depau** [comment]
AFAIK it does not load the console at all in the fb. You just connect to the USB serial with minicom, putty or something like that (make sure you're in the dialout group), or to adb if you get it working and you use that one.

I'm not the expert here, so just wait for the other people to give their opinion.

On August 3, 2014 9:56:25 AM CEST, budomino notifications@github.com wrote:

> Hey, I have a problem booting with the mr1 kernel. It gives off kernel
> messages but never loads the console. Also, the redraw speed of these
> kernel messages is sluggish and piece by piece.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/crondog/arch-flo/issues/4#issuecomment-50984525

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tina-nova** [comment]
Ok, so I tried loading minicom and screen, and both act like they're waiting for something to load in that there's absolutely nothing in screen and minicom just shows "Press CTRL-A Z for help on special keys" 
What am I doing wrong?

**Comment by depau** [comment]
I don't know, press enter, wait a little more...
You should get to a screen that says something like "nexus7 login:"

Make sure you've set everything up like crondog said in the readme.

On August 3, 2014 4:23:11 PM CEST, budomino notifications@github.com wrote:

> Ok, so I tried loading minicom and screen, and both act like they're
> waiting for something to load in that there's absolutely nothing in
> screen and minicom just shows "Press CTRL-A Z for help on special keys"
> 
> What am I doing wrong?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/crondog/arch-flo/issues/4#issuecomment-50991720

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by willcast** [comment]
When you run minicom, does the status bar say that it's online?

**Comment by tina-nova** [comment]
No, it says offline. Also, I waited an hour and pressed enter to no avail.

**Comment by willcast** [comment]
Hmm... I remember this happening before I changed fbcon_init to be a
late_initcall. Try rebuilding the kernel with  CONFIG_FRAMEBUFFER_CONSOLE=n
in config and then boot and connect again.

**Comment by tina-nova** [comment]
Setting CONFIG_FRAMEBUFFER_CONSOLE to n just makes the bootloader freeze. But I think that's what the option is supposed to do? I still get offline in minicom, so it's still a problem.

OH, I forgot to mention that mr1 kernel compilation fails with ramdump.c multiple definition errors if CONFIG_MODULES=n. I had to comment out "obj-$(CONFIG_MSM_WCNSS_SSR_8960) += wcnss-ssr-8960.o" in arch/arm/mach-msm/Makefile (as it looks like that was supposed to be the case anyway) to get it to compile. I think there's something wrong with my toolchain if you guys get to compile mr1 no problem.
EDIT: I get the same result with the "working" kernel if I set CONFIG_MODULES=n (and the same problem with ramdump.c) Seriously, is something wrong with my setup? How come you guys get to compile+run it properly?

**Comment by willcast** [comment]
There was something different to set in the config. The makefiles for WCNSS
are a convoluted mess, and it appears in both network and staging under
menuconfig. If you've only seen one, one of the settings has to be toggled.

To make wlan a module, set CONFIG_PRIMA_WLAN=m (Drivers/Staging
Drivers/Qualcomm Atheros Prima WLAN module) and keep CONFIG_WCNSS_CORE=y
(Drivers/Network device support/Wireless LAN/Qualcomm WCNSS CORE driver).
Don't set both to "M" or you'll get undefined symbols from the driver
referenced in the flo support from arch/arm/mach-msm/asus.

If you want the module built in, look at the defconfig for android, it's
built in there.

Use Linaro GCC 4.7 at most. I don't believe the tree has the 4.8 fixes
merged in.

**Comment by depau** [comment]
What do I need to edit exactly to get only wlan built-in?

**Comment by depau** [comment]
When I modprobe wlan I get "permission denied".

This is the kernel log.
http://paste.ubuntu.com/8047165/

**Comment by depau** [comment]
Can that be related to SELinux, even though I don't see any SELinux error in the dmesg? 
And how do I disable it in runtime? I can do that on Android but not on Arch.

**Comment by crondog** [comment]
Hmm im not sure what that error is. But if you want to disable selinux put in your 

--cmdline "... selinux=0"

**Comment by depau** [comment]
Thanks for the tip. I don't know what's wrong with the module because everybody else can get it going but I can't :/
I'll attach the full dmesg when I have time...

On August 18, 2014 1:10:10 AM CEST, crondog notifications@github.com wrote:

> Hmm im not sure what that error is. But if you want to disable selinux
> put in your 
> 
> --cmdline "... selinux=0"
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/crondog/arch-flo/issues/4#issuecomment-52438718

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by DelusionalLogic** [comment]
I'm having this issue as well. The paste he posted (http://paste.ubuntu.com/8047165/) is what's printed to dmsg every time you try and `modprobe wlan`

I have no idea what's wrong. I compiled it with 

```
CONFIG_MODULES=y
CONFIG_PRIMA_WLAN=m
CONFIG_WCNSS_CORE=y
```

Normally ramdump will give you an error when you try and compile that, but i went into the `arch/arm/mach-msm/Makefile` and removed `obj-y += ramdump.o` After that everything compiles and boots fine. I then `make modules` and install to somewhere. I  copy the new lib folder to the root of the arch install, and reboot.

The paste also appears on boot (with firmware.service enabled)

SELinux is off (0)

**Comment by tina-nova** [comment]
Wifi seems to work for me out of the box. The only difference is that I got my kernel from davideddu because ramdump errors happen and removing the culprit line just didn't boot fine. Nevertheless, I compiled the kernel from my device (and not my computer) and copied over the compiled modules to the proper folder.

**Comment by DelusionalLogic** [comment]
I guess i could try and compile it from the device, but that really shouldn't be a problem i don't think. Could you point me at the kernel you used? I tried the actual `Android/kernel_msm mr2` branch, and after some tinkering to get it to compile it still didn't work with wlan (`wlan not found`)

EDIT: Did you not modify the config in any way?

**Comment by DelusionalLogic** [comment]
Okay, this is very strange. Building the kernel on the device booted running a kernel without wifi actually made wifi work.

Sadly it also broke everything else. Systemd is no longer starting. but i can see in the kmsg that wlan is doing all sorts of initializing. Now i just have to figure out what it broke.

**Comment by DelusionalLogic** [comment]
Actually... Looking at the log again, it broke everything. It's not even writing to the kmsg. The message i see is the last android boot.

**Comment by willcast** [comment]
Gcc 4.6 is best. Arch has way newer

**Comment by DelusionalLogic** [comment]
I'll give it another shot on the tablet... the problem is that it takes 2-3 hours to compile on there.

I'll try compiling GCC 4.6.4 from source and give that a shot

**Comment by DelusionalLogic** [comment]
I gave GCC 3 hours to compile, and it failed. Did  you all compile the kernel on the device? because i just can't for the life of me imagine how that could be the problem.

**Comment by DelusionalLogic** [comment]
Nope, gcc4.6 will not compile on the device. 

I know this is a lot to ask, but could someone try and follow the guide from the start. I just don't get what the problem is.

**Comment by DelusionalLogic** [comment]
I am now getting the same errors as @Davideddu was getting last time he posted. I wish he had explained how to fix them (if he ever figured it out).

**Comment by depau** [comment]
@DelusionalLogic No I haven't, but I saw you solved them in the other issue. Sadly I just deleted Arch Linux because I was running out of space, I have the 16 GB version. I wish I could use both OTG and adb/serial at the same time... I currently have 3GB of free space and I don't think arch is going to fit into them. However I'll try to install it _without_ creating the image (I mean by chrooting directly into arch's root) so that it behaves like a dynamically allocated vbox virtual hard drive.

Anyway, out of curiosity, how big is your archlinux image?

**Comment by DelusionalLogic** [comment]
@Davideddu It's 10GB. I'm planning on dropping it on a USB as soon as i get evdev fixed, because currently i can't get `EmulateThirdButton` to work. It's probably going to be fun when i get that working, so i can rightclick.

**Comment by depau** [comment]
@DelusionalLogic I guess you have the 32GB version, I should have bought that one instead. I didn't think my apps would occupy so much space.
Anyway yeah, I have/had that issue too. Are you going to patch evdev?

**Comment by DelusionalLogic** [comment]
@Davideddu I'm going to figure out what is going on first, because from what i can gather it should work. I'm asking around in IRC's right now.

**Comment by depau** [comment]
@DelusionalLogic Alright. I'm going to _try_ to install Arch again in a filesystem directory. Let me know if you get it fixed. I'll try to build the kernel the way you did. Anyway I now have a USB ethernet adapter which I got working on CyanogenMod (it was just a kernel config matter to enable some driver), hopefully it will work on Arch too with the same config.

**Comment by DelusionalLogic** [comment]
@Davideddu A quick warning. Check with `ifconfig` to see if wlan is working. I didn't sync with android for me, so i configured wpa_supplicant manually.

**Comment by DelusionalLogic** [comment]
So i've found the problem in evdev. It's a problem that all driver that issue touch events have. So the good news is that it's not device specific. The bad news is that the fix is "large" compare to the third button emulation (It's basically a complete rewrite). I'll try and see if i can fix it and drop a patch here before submitting it upstream.

**Comment by depau** [comment]
@DelusionalLogic Thank you.
Just for the records, I just finished installing my arch chroot directly into Android's filesystem. I had to tweak a little bit the chroot and install-arch scripts (lots of issues :/ like /data mounted with nosuid, noalotofstuff which prevented sudo from running, fuser killing zygote for some reason every time I exited the chroot, etc.)
It seems working at the moment, I havent' booted it yet though. I managed to build both the kernel and the modules with no error, including the driver for my ethernet stick (yayy, I can use ssh!)
At the moment I'm building the Pantheon desktop. I believe it's going to be good looking with such a high resolution for one simple reason: it's based on GTK3. GTK3 apps have run soooooo smoothly the last time I tried, they didn't bother with the DPI (just set the right physical screen size in xorg.conf), they were touch friendly and relatively fast.
Hopefully it will work without hardware acceleration/will let me use a custom WM.

**Comment by DelusionalLogic** [comment]
@Davideddu I kinda sorta have it working. I'm not going to release it yet, since it's still an awful hack. At least evdev is pretty simple. Basically it works right now, but it's flaky. I'm probably going to release some half baked hack at some point, then fix it up later.

It basically comes down to the touch screen being classified as something with more than one button, and evdev therefore not parsing it early enough. That coupled with a strange placement of the `ThirdButton` handler.

**Comment by depau** [comment]
@DelusionalLogic Ok, good, let me know when a patch is ready. As I told you I'm building Pantheon, I'm keeping the built packages if you want them.

**Comment by depau** [comment]
I finally managed to get ArchLinux working without using an image. I had to tweak the install scripts and the initramfs a little bit, but I did it. I build a bunch of Pantheon components. The gala window manager doesn't work, it's looking for libwayland-egl.so.1, which we don't have. Copying it from ALARM's mesa makes it not crash, but it doesn't work either.

wlan module works, I just can't connect to networks. With the shared configuration, I run wpa_supplicant, it says it's connecting to the AP and it fails. I think dhcpcd is the cause of this issue. BTW I also installed networkmanager to manage the networks through the GUI.

**Comment by DelusionalLogic** [comment]
if you want to run network manager you should not be running dhcpcd or wpa_supplicant. I'd advise you to create a small wpa_supplicant config. the arch wiki has excellent examples of how to do this with wpa_cli.

**Comment by willcast** [comment]
Are you using the nl80211 version of WPA supplicant?

**Comment by DelusionalLogic** [comment]
Nope. But the regular version works just fine if you create a configuration
file.

**Comment by depau** [comment]
I didn't create a configuration, however I disabled both wpa_supplicant and dhcpcd and network manager works.
Now I'm looking for an elementary OS indicator.

**Comment by depau** [comment]
Problem solved; wifi, bluetooth, etc are working.
